{\rtf1\ansi\ansicpg1252\cocoartf2578
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww14020\viewh15760\viewkind0
\pard\tx566\tx1133\tx1700\tx2267\tx2834\tx3401\tx3968\tx4535\tx5102\tx5669\tx6236\tx6803\pardirnatural\partightenfactor0

\f0\fs36 \cf0 (djangoEnv) Sajas-iMac:single_model_orm saja$ python3 manage.py shell\
Python 3.9.4 (v3.9.4:1f2e3088f3, Apr  4 2021, 12:32:44) \
[Clang 6.0 (clang-600.0.57)] on darwin\
Type "help", "copyright", "credits" or "license" for more information.\
(InteractiveConsole)\
>>> from users_app.models import *\
>>> User.objects.create(first_name="Saja",lastname="Alhimiary",email_address="sajaalhimiary@yahoo.com",age=28)\
Traceback (most recent call last):\
  File "<console>", line 1, in <module>\
  File "/Users/saja/Documents/CodingDojo/python_stack/my_environments/djangoEnv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method\
    return getattr(self.get_queryset(), name)(*args, **kwargs)\
  File "/Users/saja/Documents/CodingDojo/python_stack/my_environments/djangoEnv/lib/python3.9/site-packages/django/db/models/query.py", line 451, in create\
    obj = self.model(**kwargs)\
  File "/Users/saja/Documents/CodingDojo/python_stack/my_environments/djangoEnv/lib/python3.9/site-packages/django/db/models/base.py", line 503, in __init__\
    raise TypeError("%s() got an unexpected keyword argument '%s'" % (cls.__name__, kwarg))\
TypeError: User() got an unexpected keyword argument 'lastname'\
>>> User.objects.create(first_name="Saja",last_name="Alhimiary",email_address="sajaalhimiary@yahoo.com",age=28)\
<User: User object (1)>\
>>> User.objects.create(first_name="Zaid",last_name="Alshammari",email_address="zaid@yahoo.com",age=22)   <User: User object (2)>\
>>> User.objects.create(first_name="Layla",last_name="Askar",email_address="Layla@yahoo.com",age=22)\
<User: User object (3)>\
>>> User.objects.all()\
<QuerySet [<User: User object (1)>, <User: User object (2)>, <User: User object (3)>]>\
>>> User.objects.last()\
<User: User object (3)>\
>>> User.objects.first()\
<User: User object (1)>\
>>> c=User.pbjects.get(id=3)\
Traceback (most recent call last):\
  File "<console>", line 1, in <module>\
AttributeError: type object 'User' has no attribute 'pbjects'\
>>> c=User.objects.get(id=3)\
>>> c.last_name="Pancakes"\
>>> c.save()\
>>> c=User.pbjects.get(id=2)\
Traceback (most recent call last):\
  File "<console>", line 1, in <module>\
AttributeError: type object 'User' has no attribute 'pbjects'\
>>> c=User.objects.get(id=2)\
>>> c.delete()\
(1, \{'users_app.User': 1\})\
>>> User.objects.all()\
<QuerySet [<User: User object (1)>, <User: User object (3)>]>\
>>> >>> User.objects.all().order_by("first_name")\
Traceback (most recent call last):\
  File "<console>", line 1, in <module>\
AttributeError: type object 'User' has no attribute 'objecbjects'\
>>> User.objects.all().order_by("first_name")\
<QuerySet [<User: User object (3)>, <User: User object (1)>]>\
>>> User.objects.all().order_by("-first_name")\
<QuerySet [<User: User object (1)>, <User: User object (3)>]>\
>>> }